name: process

on:
  schedule:
    - cron: 55 5 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      NAMESERVERS: ${{ secrets.NAMESERVERS }}

    steps:
      - uses: actions/checkout@v2

      - name: pull from source
        run: >
          wget
          https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
          https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
          https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        
      - name: convert
        run: sed -e 's|\(.*\)|\1 $(NAMESERVERS)|' accelerated-domains.china.conf google.china.conf apple.china.conf > forwarding-rules.txt
        
      - name: commit
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'action@github.com'
          git add forwarding-rules.txt
          git commit -m "Update" || echo -n ""
          
      - name: push
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}
