name: process

on:
  schedule:
    - cron: 55 5 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pull from source
        run: wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        
      - name: process
        run: cut -d'/' -f 2 accelerated-domains.china.conf | awk '{ printf $1; print " 119.29.29.29" }' >forwarding-rules.txt
        
      - name: commit
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'action@github.com'
          git add forwarding-rules.txt
          git commit -m "Update" || echo -n ""
          
      - name: push
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}
